"""init

Revision ID: c9618bc4c5da
Revises: 
Create Date: 2024-10-20 13:54:30.981128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c9618bc4c5da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortlink',
    sa.Column('long', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('short', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shortlink')
    # ### end Alembic commands ###
